### ISSUE TITLE
[Suggestion] Add Tug in Composer private repositories

### ISSUE THREAD

**Issue by francoispluchino** [jakoch/awesome-composer#47]
Hi @jakoch,

I just came across your site referencing a multitude of plugins and tools for Composer. Given that I noticed that there were 2 of my plugins in your list, I would therefore like to submit a suggestion to you, because I think that this tool for Composer can be useful for a certain number of developers. Indeed, and even if this tool has been around for several years and is used in production for a while, it has been recently updated to make it easier its use.

This free and open-source tool, it's [Tug](https://github.com/fxpio/tug), a Composer private registry for private PHP packages (on Github or Gitlab services) that is hosted on your Amazon Web Services Account with the Serverless services for a financial cost extremely low, see free. Moreover, it can be installed in a few clicks, and of course, you can manage all features with the Progressive Web Application for desktop and mobile.

The main idea of this tool is to have an intermediary between the management of its own server Packagist, or the use of a third party service, and the simple static packages generator like Satis. That is, do not be worried about updating package versions and SHA1s of the branches, while avoiding the cost of server maintenance and execution, or the high cost of third-party services.

If you think it might be interesting to add this tool in your list, it might be appropriate to put it in a new section `Private repositories` in the `Composer Repositories` category. What do you think?

In all cases, thanks for your great list!

**Comment by jakoch** [comment]
Hey François, i've added Tug to the list. 
Thank you for contributing and the detailed explaination 👍 ❤️
