### ISSUE TITLE
Some entries are unmaintained or duplicate

### ISSUE THREAD

**Issue by Goldziher** [jakoch/awesome-composer#50]

**Comment by jakoch** [comment]
That means you already found them and are not posting them, to help in any which way.. 

Thank you for nothing. 
Have a nice day.

**Comment by Goldziher** [comment]
Certainly, asshole

**Comment by jakoch** [comment]
I've been expecting it.

You openend an issue not being able to provide constructive feedback or giving a concise description.
It's like going to any other repository, opening an issue named "your software contains bugs, maintain it"
and at that level of vagueness, it's simply trolling.

Now you switched from trolling to insulting. That's plain simple unprofessional, unacceptable behavior.
This repository follows a [Code of Conduct](https://github.com/jakoch/awesome-composer/blob/master/code-of-conduct.md#our-standards) and as maintainer of this community project i see it as my responsibility 
to use this opportunity to remind you about professional behavior as a software dev.

Please learn or refresh your memory on [how to write a good bug report](https://instabug.com/blog/how-to-write-a-bug-report-the-ideal-bug-report/). 

It’s nice that you did good work and found an issue, but do not use this credit for attack. Be better. 

Sincerely, Jens
